### PR TITLE
Depend on the official integration at twbs:bootstrap

### PR DESCRIPTION
**Pull request by mizzao**
Updated the package to use `twbs:bootstrap` instead of `mizzao:bootstrap-3`.

### CODE REVIEW

**Comment by mizzao** [comment]
Also made the dependency weak so that other packages like `nemo64:bootstrap` can be used (mizzao/meteor-x-editable-bootstrap#1), thanks @1024kilobyte.

**Comment by nate-strauser** [comment]
thanks!

**Comment by paulbalomiri** [comment]
Could you also add a weak dependency for `nemo64:bootstrap`?

**Comment by 1024kilobyte** [comment]
What do you need it for? The current dependency for bootstrap is already weak, so you can use any bs package you want, as @mizzao already mentioned before: ```Also made the dependency weak so that other packages like nemo64:bootstrap can be used```

**Comment by paulbalomiri** [comment]
Yes, but the weak dependency influences the load order. Right now i cannot use `nemo64:bootstrap` because the `popover.js` file is loaded after this package.

 The weak dependency would fix the  load order. See this issue in [nemo64/meteor-bootstrap](https://github.com/Nemo64/meteor-bootstrap/issues/14).

**Pull request merged**
